version: "3.8"

services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile
    image: directus
    container_name: derp-directus
    ports:
      - "8055:8055"
    env_file:
      - .env